### ISSUE TITLE
<US 02.07.01> Sign up for an Event

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#103]
US 02.07.01 As an attendee, I want to sign up to attend an event from the event details (as in I promise to go).
 
Acceptance Criteria:
1. see the event details and click on a button to sign up!
2. after signing up, the event will appear in the upcoming event list in user home page

**Comment by jubinvillecameron** [comment]
This should be working right now, but there is a bug in the code (more like unimplemented feature due to time crunch where it doesnt add you to the proper lists and upload it to the database)
