### ISSUE TITLE
Decouple the cached Events in Placeholder app

### ISSUE THREAD

**Issue by jubinvillecameron** [CMPUT301W24T05/PlaceHolderProjectName#129]
Might want to use callbacks or a different way of treating how we send data to different fragments. Looking at the Placeholder app object the design of the cached variables is very hacky and not the best design. However it is very quick to make and allows us to implement things fast, and to fix it would take a lot of time. So not alltogether necessary.

**Comment by jubinvillecameron** [comment]
@maximum-maxness whats your opinion on this

**Comment by maximum-maxness** [comment]
I completely agree that the PlaceholderApp way we've been doing doesn't feel right, but I'm not entirely sure how else we can do it if we want a persistent hashmap of events between activities. We'll have to do some more research on the best design to fix the problem, I guarantee that there is some sort of program design that accommodates what we're trying to do. We could experiment with intents, but I don't think passing that much data is what they're intended for.

**Comment by jubinvillecameron** [comment]
@maximum-maxness I think keeping the persistent hashmap of events between activities is fine. We can even download and store the profile picture as well. But for the cachedEvent/Profile variables we should probably just use bundles

**Comment by jubinvillecameron** [comment]
No time to do this
