### ISSUE TITLE
<US 04.06.01> Be able to browse images

### ISSUE THREAD

**Issue by maximum-maxness** [CMPUT301W24T05/PlaceHolderProjectName#13]
US 04.03.01 As an administrator, I want to be able to browse images.

Coincides with #10 

We can browse through all images within firebase or do we want a flow where we select an event and see all of its associated images?
Can we browse all associated images within a user?

This needs clarification.

**Comment by jubinvillecameron** [comment]
All images are able to be viewed and such just visual bugs need to be solved
