### ISSUE TITLE
<US 02.02.02> Remove Profile Picture

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#15]
US 02.02.02 As an attendee, I want to remove profile pictures if need be.

Acceptance Criteria:
1. First click on the profile button on the home page to go to the profile_editing_page
2. Click on the delete button to delete the profile picture
3. The previous profile picture is not shown on the profile_editing_page anymore.
4. When clicking on the save button, the profile picture is removed from the database as well, and you goes back to the home page.
5. The next you go to the profile_editing_page, you will see the profile picture is removed from the page.

**Comment by jubinvillecameron** [comment]
this is working just needs testing
