### ISSUE TITLE
Get a list of Registered Users (Interested) in the Event Document

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#158]
In the event object / document, added a attribute (a list) of Strings of userID who signed up for the event.
In the profile object / document, update the list of interested Event after signing up for an event

**Comment by jubinvillecameron** [comment]
pretty sure this is already implemented isnt it?
Isnt the key for the hashmap in the getAttendees() the string for the profiles?

**Comment by Galvinn** [comment]
That's for attendees, this one is for users who signed up

**Comment by jubinvillecameron** [comment]
@Galvinn so people who are interested?

**Comment by Galvinn** [comment]
Yes!

**Comment by Galvinn** [comment]
I think I will close this issues as I finished it already
