### ISSUE TITLE
<US 02.02.03> Update Profile Information

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#16]
US 02.02.03 As an attendee, I want to update information such as name, homepage, and contact information on my profile.

Acceptance criteria:
1. First click on the profile button on the home page to go to the profile_editing_page
2. Change and type in the text boxes for Contact, Name, and Homepage.
3. Click on the save button and this will update the information and go back to the home page.
4. The next time you go to the profile_editing_page, you will see the update information.

**Comment by jubinvillecameron** [comment]
this is finished thanks galvin
