### ISSUE TITLE
<US 02.03.01> Receive Push Notification

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#17]
US 02.03.01 As an attendee, I want to receive push notifications with important updates from the event organizers.

Acceptance Criteria:
1. Create the Android Project that receives the Push Notification
2. Create the Firebase Server that sends the Push Notification
3. Connect the Firebase Server and the Android Project
4. Testing the Push Notification
5. Post the notifications in the announcement tab for attendees to see.
6. Whenever the event organizer send out a notification, attendee will receive the notification.

**Comment by jubinvillecameron** [comment]
This is really really hard
