### ISSUE TITLE
Create tests for everything

### ISSUE THREAD

**Issue by jubinvillecameron** [CMPUT301W24T05/PlaceHolderProjectName#173]
Don't know in particular what hasn't been tested yet, but need tests for:

- notifications
- admin page
- intent tests
- event organizer page
- etc

**Comment by Anthony-Mirza** [comment]
Created unit test for QRCode class and Event class so far.

Will work on creating even more unit tests for Event class, as well as tests for profile, notification, milestones, firebase, and QR code scanner (depending on how feasible it actual is).

Will begin intent testing as soon as UI is close to completion.

**Comment by Anthony-Mirza** [comment]
Event, Profile, and QRCode class done. Starting on Notification class now.
