### ISSUE TITLE
Card View (including statistics) for Organizer Page

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#180]
Heart means the number of registered, and the human figure is attended/Max_capacity.
1. Differentiate between hostedEvent layout and joined event layout. Added a conditional statement in the EventAdpater.java
 <img width="906" alt="Screenshot 2024-04-02 at 01 53 23" src="https://github.com/CMPUT301W24T05/PlaceHolderProjectName/assets/117534018/46a85088-a3c7-4600-934f-1aff2092427f">

2. The Layout I created is event_card_hosted.xml

2. Created a HostedEventCardViewHolder (extend EventCardViewHolder) to add some statistics and the poster image
<img width="707" alt="Screenshot 2024-04-02 at 01 54 24" src="https://github.com/CMPUT301W24T05/PlaceHolderProjectName/assets/117534018/3cdd388c-ffe4-4183-9dc9-c34526764bda">

**Comment by maximum-maxness** [comment]
this is complete!
