### ISSUE TITLE
Add char limit to event names / profile names

### ISSUE THREAD

**Issue by jubinvillecameron** [CMPUT301W24T05/PlaceHolderProjectName#184]
This is up for debate, but In order to make sure that event names look nice in our UI and such, we should either limit this on event creation. Or truncate in all of our displays for events / profile names

**Comment by Galvinn** [comment]
setting a limit for profile name does not work,

**Comment by Anthony-Mirza** [comment]
Not necessary to implement this. So it's best to close it for the sake of time.
