### ISSUE TITLE
<US 02.06.01> No Login, No Username, No Password

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#20]
US 02.06.01 As an attendee, I do not want to login to the app. No username, no password.

Acceptance Criteria:
1. When a user uses the app for the first time, they are prompted to enter their name only without thinking up with a username and password. The app will automatically generate a profile specific to this device.
2. The second the user opens the app on the same device, they will be taken directly to the homepage.
3. Since we create a profile per device, all the information specifically to the device (profile) is shown.
4. The app does not ask the user to input their username and password in order to log in.

**Comment by jubinvillecameron** [comment]
This is working with the initial activity
