### ISSUE TITLE
<US 03.02.01> Enable / Disable Geolocation Tracking for Event Verification

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#21]
Not sure how to implement
There should be a button on the main page for both Organizer and Attendee to click to turn on or off.

**Comment by jubinvillecameron** [comment]
https://developers.google.com/maps/documentation/geolocation/overview#:~:text=The%20Geolocation%20API%20is%20a,result%20for%20each%20valid%20input.

we can use the built in geolocation in android
