### ISSUE TITLE
Click on Profile Icon to Update Profile

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#25]
As a user (including all 3 roles), the user can click on the 'Profile' icon on the home page and update their user information. 

To update user information, refer to the issues below: 
<US 02.02.01>
<US 02.02.02>
<US 02.02.03>

For the administrator, there will be an additional button "administrator" for them to gain access to the page designated for the administrator.

**Comment by jubinvillecameron** [comment]
this is working and going to database
