### ISSUE TITLE
View a list of my events and my organized event

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#26]
As a user I want to view a list of the events I am attending and the list of events I have organized.

They can click on a specific event to see details.
They can click on the "Create a New Event" button to go to the event-creating page.
They can click on the "Join a New Event" button to go to the QR code Scanner page.

When a user creates/joins a new event, the new event will be put into the corresponding event list.

**Comment by maximum-maxness** [comment]
This is mostly complete. The joined events listview works! The organized events listview is implemented, but created events are not added to the profile yet so there is nothing to display. Either way, both are implemented and I will mark this issue as completed!
