### ISSUE TITLE
<US 04.07.01> Gain Access to Administrator Privilege Page

### ISSUE THREAD

**Issue by Galvinn** [CMPUT301W24T05/PlaceHolderProjectName#27]
As an administrator, there is an "administrator" button on the edit profile page
After clicking on it, the administrator will taken to the main page for admin with 3 options:
Browse Events
Browse Profiles
Browse Images

**Comment by jubinvillecameron** [comment]
don't know the status of this @Galvinn how close are you to being done?

**Comment by maximum-maxness** [comment]
This is completed!
