### ISSUE TITLE
<US 01.01.02> Upload event poster

### ISSUE THREAD

**Issue by toluLajide** [CMPUT301W24T05/PlaceHolderProjectName#29]
As an organizer, I want to upload a poster advertising my event during the event creation process onto the database. This poster will be displayed on the event details pages that is viewable by the attendee

**Comment by Anthony-Mirza** [comment]
Reworded this issue in the format from eClass.

**Comment by jubinvillecameron** [comment]
We are able to upload event posters currently but have no UI for it. But basic functionality is working in the ImageDatabase Branch
