### ISSUE TITLE
<US 01.01.02> As an organizer, I want the option to reuse an existing QR code for attendee check-ins.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#32]
Acceptance criteria:

1. After the organizer selects the next button on the event poster uploading page, they're taken to another page where they're prompted to either scan and reuse an existing QR code or to generate a brand new one to use for attendee check-ins.
2. The organizer selects to scan and reuse an existing QR code.
3. The organizer is prompted to scan the existing QR code with their phone's camera.
4. The user scans the QR code. 
5. Upon success the organizer confirms their choice and continues with the event creation process.

**Comment by jubinvillecameron** [comment]
see #113 for a continuation of requirements for this
