### ISSUE TITLE
<US 01.01.01.b> As an organizer, I want to create a new event and generate a unique QR code for attendee check-ins.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#33]
Acceptance criteria:

1. During event creation, organizer is prompted to either generate a brand new QR code or reuse a pre-existing one for attendee check-in. 
2. Organizer selects option to generate a brand new one.
3. A new QR code is generated for attendee check-in and the QR code is operational for all attendees wishing to check into event.

**Comment by toluLajide** [comment]
User can choose to generate this QR code during the event creation process

**Comment by jubinvillecameron** [comment]
generating qr code s in general work properly
