### ISSUE TITLE
<US 01.07.01> As an organizer, I want to create a new event and generate a unique promotion QR code that links to the event description and event poster in the app.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#34]
Acceptance criteria:

1.  The organizer completes all the steps in the event creation process (inputting event details, uploading event poster, QR code generation) and create the event.
2. The promotional QR code is automatically generated.
3. The organizer is directly led to a page where they can view both the check-in QR code and promotional QR code.
4. Under the promotional QR code,  the user has the option to select the share button to share the QR code with other people.

**Comment by jubinvillecameron** [comment]
just finished this, adding funtionality to generate and save
