### ISSUE TITLE
<US 01.03.01.c> As an organizer, I want to have the option to pin a specific notification to the notification board for all attendees to see.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#36]
Acceptance criteria:

1. Organizer navigates to their event's home page and selects the button to access announcements. 
2. The organizer then selects the button to make a new announcement. 
3. Under the text box for the new announcement, the organizer has the option to pin the announcement.
4. Organizer selects this option and confirms announcement. 
5. Announcement is pinned to the top of the announcement board for the organizer and all attendees.

**Comment by jubinvillecameron** [comment]
This is working properly
