### ISSUE TITLE
<US 01.03.01.a> As an organizer, I want to send notifications to all attendees through the app.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#38]
Acceptance criteria:

1. Organizer navigates to their event's homepage and select the announcements button.
2. The organizer is able to view a list a of all their previous announcements. At the bottom of the list there is a button to create a new announcement. The organizer selects this button.
3. The organizer is prompted to enter a text message into a text box to send to all attendees, the organizer does so. 
4. Below the text box, the user selects the option to notify all attendees. After, they confirm their announcement.
5. All attendees are notified of the announcement.

**Comment by jubinvillecameron** [comment]
Currently a user is able to see notifications but not push notifications, will need to keep working on this

**Comment by jubinvillecameron** [comment]
There is functionality in main to do this, but no main page which links to everything.

**Comment by jubinvillecameron** [comment]
Push Notifications are needed: Some websites to get it working  
https://firebase.google.com/docs/functions
https://firebase.google.com/docs/cloud-messaging/android/receive#java
