### ISSUE TITLE
<US 01.05.01> As an organizer, I want to track real-time attendance and receive alerts for important milestones.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#42]
Acceptance criteria:

1. Organizer navigates to their event's home page and selects attendance. 
2. Organizer is able to view their event's attendance and witness updates in real time.
3. Organizer exclusively receives notifications each time a milestone for their event is achieved.

**Comment by Anthony-Mirza** [comment]
@toluLajide @jubinvillecameron Is this finished? Can we close this issue yet?

**Comment by jubinvillecameron** [comment]
I'm not working on this currently I would ask Tolu @Anthony-Mirza

**Comment by jubinvillecameron** [comment]
I'm not working on this currently I would ask Tolu @Anthony-Mirza

**Comment by Anthony-Mirza** [comment]
Still buggy, but the current implementation according to Tolu passes the acceptance criteria.
