### ISSUE TITLE
<US 01.06.01> As an organizer, I want to share a generated QR code image to other apps so I can email or update other documents with the QR code.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#44]
Acceptance criteria:

1. Upon confirming event creation, the organizer is directed to a page with their check-in QR code and informational QR-code. 
2. Below each QR code the organizer has the option to share that QR code with other apps. The organizer selects this button.
3. The organizer directed to a fragment where they can share their QR code with another app.
4. Alternatively, the organizer navigates to their event's homepage and selects the button to access their QR codes. Upon doing so, begin from step two.

**Comment by jubinvillecameron** [comment]
Currently only downloading the QR Code is working, not sending it to other apps. Consider looking at this to fully implement it.
https://developer.android.com/training/sharing/send
