### ISSUE TITLE
<US 01.11.01> As an organizer, I want to OPTIONALLY limit the number of attendees that can sign up for an event.

### ISSUE THREAD

**Issue by Anthony-Mirza** [CMPUT301W24T05/PlaceHolderProjectName#99]
Acceptance criteria:

1. During the event creation process, the organizer is prompted to fill out the event details forms.
2. If the organizer keeps the capacity field blank, the capacity of their event will be unlimited.
3. Otherwise, if they input a specific number, then their event's capacity will be limited to the finite number they specified in the event creation process.

**Comment by jubinvillecameron** [comment]
There is a bug, where this is not optional. it is mandatory to set it, need to change it on update

**Comment by jubinvillecameron** [comment]
I don't know if we changed how event creation works!
@maximum-maxness did you fix everything?
